#language: generic
#sudo: required
#services:
#  - docker

#before_install:
#  - docker build -t drout/docker-react -f Dockerfile.dev .

#script:
#  - docker run -e CI=true drout/docker-react npm run test